package:
  name: sstmap
  version: v1.1
source:
  path: ../../

requirements:
  build:
    - python
    - numpy
    - scipy
    - setuptools
    - mdtraj
    - parmed

  run:
    - python
    - numpy
    - scipy
    - mdtraj
    - parmed

about:
  home: https://github.com/kamran-haider
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: Python tools for analysis of water molecules in MD trajectories.
